# Generated by Django 4.2.4 on 2023-09-07 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('photo', models.ImageField(null=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фото категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Доктора',
            },
        ),
        migrations.CreateModel(
            name='Procedures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('results', models.TextField(blank=True, null=True, verbose_name='Результаты')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Продолжительность')),
            ],
            options={
                'verbose_name': 'Процедура',
                'verbose_name_plural': 'Процедры',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='procedures.categories')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='procedures.procedures')),
            ],
        ),
        migrations.AddField(
            model_name='procedures',
            name='categories',
            field=models.ManyToManyField(related_name='categories', through='procedures.Relation', to='procedures.categories'),
        ),
    ]
