# Generated by Django 4.2.4 on 2023-09-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0003_alter_categories_photo_alter_categories_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedures',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='procedures',
            name='categories',
            field=models.ManyToManyField(related_name='procedures', through='procedures.Relation', to='procedures.categories'),
        ),
    ]
