# Generated by Django 4.2.4 on 2023-09-09 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0004_procedures_is_published_alter_procedures_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedures',
            name='is_published',
        ),
    ]
