# Generated by Django 4.2.4 on 2023-09-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0005_remove_procedures_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedures',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
