# Generated by Django 4.2.4 on 2023-09-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0006_procedures_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedures',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
