# Generated by Django 4.2.4 on 2023-09-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0009_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Телефон'),
        ),
    ]
