# Generated by Django 4.2.4 on 2023-09-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0011_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='message',
            new_name='question',
        ),
        migrations.AddField(
            model_name='questions',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
