# Generated by Django 4.2.4 on 2023-09-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0012_rename_message_questions_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
    ]
