# Generated by Django 4.2.4 on 2023-09-26 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0013_questions_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'verbose_name': 'Заявка на обратный звонок', 'verbose_name_plural': 'Заявки на обратный звонок'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Вопросы и отзывы', 'verbose_name_plural': 'Вопросы и отзывы'},
        ),
    ]
