# Generated by Django 4.2.4 on 2023-09-26 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0015_questions_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['created_at'], 'verbose_name': 'Вопросы и отзывы', 'verbose_name_plural': 'Вопросы и отзывы'},
        ),
    ]
